Dataloader:
  download: True
  url: 'https://github.com/RossiyaSegodnya/ria_news_dataset/raw/master/ria.json.gz'
  path: 'data/'
  name: 'ria.json.gz'
  max_txt_length: 98
  samples: 100000

Embedder:
  download: True
  use_url: "https://tfhub.dev/google/universal-sentence-encoder/4?tf-hub-format=compressed"
  use_directory: 'models/use'
  use_file_name: 'use_model_v4.tar.gz'
  tsne_config:
    n_jobs: -1
    n_components: 2
    verbose: 1

Clustering:
  directory: 'result/'
  cluster_picture_name: 'clusters.html'
  result_data_file_name: 'result_df.csv'
  center_replics_file_name: 'center_replics.json'
  part_to_plot: 0.1
  bgm_config:
    n_components: 50
    random_state: 42
    verbose: 1
    max_iter: 5000

Splitter:
  path_to_save_data: 'data/'
  min_freq: 1
  test_size: 0.1
  batch_size: 64

model:
  EMB_DIM: 128
  HID_DIM: 256 # each conv. layer has 2 * hid_dim filters
  ENC_LAYERS: 1 # number of conv. blocks in encoder
  DEC_LAYERS: 1 # number of conv. blocks in decoder
  ENC_KERNEL_SIZE: 15 # must be odd!
  DEC_KERNEL_SIZE: 2 # can be even or odd
  ENC_DROPOUT: 0.3
  DEC_DROPOUT: 0.3