Dataloader:
  url: 'https://github.com/RossiyaSegodnya/ria_news_dataset/raw/master/ria_1k.json'
  path: 'data/'
  name: 'ria_1k.json'
  max_txt_length: 500
  samples: 900

Embedder:
  use_url: "https://tfhub.dev/google/universal-sentence-encoder/4"
  tsne_config:
    n_jobs: -1
    n_components: 2
    verbose: 1

Clustering:
  directory: 'result/'
  cluster_picture_name: 'clusters.html'
  result_data_file_name: 'result_df.csv'
  center_replics_file_name: 'center_replics.json'
  part_to_plot: 0.1
  bgm_config:
    n_components: 50
    random_state: 42
    verbose: 1
    max_iter: 5000

Splitter:
  path_to_save_data: 'data/'
  min_freq: 2
  test_size: 0.2
  batch_size: 2

model:
  EMB_DIM: 2
  HID_DIM: 4 # each conv. layer has 2 * hid_dim filters
  ENC_LAYERS: 10 # number of conv. blocks in encoder
  DEC_LAYERS: 10 # number of conv. blocks in decoder
  ENC_KERNEL_SIZE: 3 # must be odd!
  DEC_KERNEL_SIZE: 3 # can be even or odd
  ENC_DROPOUT: 0.25
  DEC_DROPOUT: 0.25